# -*- coding: utf-8 -*-
'''
Here is the script for the lottery program.
It aims to assign all kinds of prizes fairly (randomly) to the students participating in this activity.
The results of the lottery will be generated by the program and saved in the result.txt file.
Good luck to you all!
'''
import numpy as np
import random

# phone numbers from students
phone_ids = []
for line in open("./phone_numbers.txt", "r"):
    line = line.strip('\n')
    phone_ids.append(line)

# prize settings
prizes = ['1',
          '2', '2', '2', '2',
          '3', '3', '3', '3', '3', '3', '3', '3', '3', '3',
          '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
          '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
          '5', '5', '5', '5', '5', '5', '5', '5', '5', '5']

# to store the lucky guys of each award
result1 = []
result2 = []
result3 = []
result4 = []
result5 = []

# randomly shuffle list prizes in place
prizes_idx = np.arange(len(prizes))
# idx = np.random.choice(prizes_idx, size=len(prizes), replace=False)
random.shuffle(prizes)

# store the lottery results to each group
result1.append(['Phone number', 'Award level'])

for i in range(len(phone_ids)):
    if   (prizes[i] == str(1)):
        result1.append([phone_ids[i], 'The first prize!'])
    elif (prizes[i] == str(2)):
        result2.append([phone_ids[i], 'The second prize!'])
    elif (prizes[i] == str(3)):
        result3.append([phone_ids[i], 'The third prize!'])
    elif (prizes[i] == str(4)):
        result4.append([phone_ids[i], 'The fourth prize!'])
    elif (prizes[i] == str(5)):
        result5.append([phone_ids[i], 'Thanks for your participation!'])

# write file to save
with open('./result.txt', 'w') as f:
    for item in result1:
        f.write(str(item))
        f.write('\n')
    for item in result2:
        f.write(str(item))
        f.write('\n')
    for item in result3:
        f.write(str(item))
        f.write('\n')
    for item in result4:
        f.write(str(item))
        f.write('\n')
    for item in result5:
        f.write(str(item))
        f.write('\n')
f.close()
